### ISSUE TITLE
Making token raises TypeError

### ISSUE THREAD

**Issue by ImLucasBrown** [nxt-dev/nxt#43]
**Describe the bug**
In rare cases its possible for `token_content` to be `None`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version API `v0.8.1`

**Additional context**
```
 Traceback (most recent call last):
File "c:\users\suesa\appdata\local\programs\python\python37\lib\site-packages\nxt_editor\dockwidgets\property_editor.py", line 1469, in mouseMoveEvent
token = tokens.make_token_str(attr_name)
File "c:\users\suesa\appdata\local\programs\python\python37\lib\site-packages\nxt\tokens.py", line 59, in make_token_str
return TOKEN_PREFIX + token_content + TOKEN_SUFFIX
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by ImLucasBrown** [comment]
I could never repro the bug as described by Sue. However I believe its been fixed.
